application: javascriptstopwatch
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /res
  static_dir: res

- url: /js
  static_dir: js

- url: .*
  script: main.py
